name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: create s3 bucket and dynamodb table locking
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # defaults:
    #   run:
    #     working-directory: ./backend
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Create s3 bucket
        working-directory: ./backend
        run: |
          terraform init
          terraform apply
      
      #     # terraform init
      #     # terraform apply -auto-approve
      # - name: Terraform init
      #   run: terraform init 

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Create ec2
        working-directory: /test/my_ec2
        run: |
          terraform init
          terraform apply
          # cd ./backend
          # terraform init
          # terraform apply -auto-approve
      # - name: Terraform init
      #   run: terraform init 

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve